nodeLinker: "node-modules"

# Configuración para Railway/Docker
enableGlobalCache: false
enableMirror: false

# Optimizaciones para CI/CD
enableTelemetry: false
logFilters:
  - code: "YN0002"
    level: discard
  - code: "YN0013"
    level: discard

# Configuración de red para Railway
httpTimeout: 60000
