[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "${{ RAILWAY_PORT || 3000 }}"

# Configuración específica para Yarn
[build.nixpacksConfigOverride]
providers = ["node"]

[build.nixpacksConfigOverride.phases.build]
cmds = ["yarn install --frozen-lockfile", "yarn build"]

[build.nixpacksConfigOverride.phases.start]
cmd = "yarn start"