[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"

# Railway automaticamente proporciona la variable PORT
# No la definimos aquí para que use el puerto asignado dinámicamente